spring:
  application:
    name: analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry_analyzer
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrate
    baseline-on-migrate: true
    baseline-version: 0

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum: DEBUG